apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hub-ms
  name: hub-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hub-ms
    spec:
      containers:
        - image: europe-southwest1-docker.pkg.dev/hexitalk/hexitalk-img-registry/hub-ms
          name: hub-ms
          env:
            - name: PORT
              value: "3006"
            - name: NATS_SERVERS
              value: "nats://nats"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: hub-ms-secrets
                  key: DATABASE_URL
          resources: {}
status: {}
