apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: socket-ms
  name: socket-ms
spec:
  ports:
  - name: "3100"
    port: 3100
    protocol: TCP
    targetPort: 3100
  selector:
    app: socket-ms
  type: NodePort
status:
  loadBalancer: {}
